; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Mon Dec 23 2019 10:22:33 GMT+0100 (Mitteleuropäische Normalzeit)


; run /filaments/<filament name>/config.g
M703

; Wait for set temperatures to be reached
M116 P0

